name: workiva_analysis_options
version: 1.5.0
homepage: https://github.com/Workiva/workiva_analysis_options
description: Workiva's shared static analysis options.

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  test: ^1.15.7
  yaml: ^3.1.0
